credentials:
  usernames:
    john:
      email: john@example.com
      name: John Doe
      password: $2b$12$eImiTXuWVxfM37uY4JANjQ==   # (Hashed password)
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
    - john@example.com

